Feature/NQ-865: Adds support for Verilator waiver files in FList tool
NuQuantum/edalize-plugins pull request #1
Opened 2024-03-06 14:26 UTC by Jonah-Foley

https://nu-quantum.youtrack.cloud/issue/NQ-866/Add-support-for-Verilator-within-Edalize-cocotb-simulation-flow Describes the scope of the change.

With the current implementation, if a parent core file should include all of its children's waiver files upon a call to `flist`, then each of the children should include the ternary `target_flist ? (verilator_waivers)` in their default target's filesets i.e. 

The child must define:

```
targets:
  default: &default
    filesets:
      - rtl
      - tool_verilator ? (verilator_waivers)
      - target_flist ? (verilator_waivers)
    toplevel: example
```

This is demonstrated in the example in `tests/flist`. It seems you cannot or flags together .. e.g. it would be nice to be able to do `(tool_verilator | target_flist) ? (verilator_waivers)` but that does not seem to work.

2024-03-06 14:29 UTC, Jonah-Foley commented
@shareefj There is scope for more rigorous testing to be done here, let me know if you think it's necessary to implement.

2024-03-11 13:08 UTC, shareefj requested changes
Just the one comment about a print command.

2024-03-11 14:01 UTC, Jonah-Foley commented on src/edalize/tools/flist.py
> +            print(file)
Yes, fixed.

2024-03-11 20:38 UTC, shareefj approved these changes

2024-03-11 20:39 UTC, merged